# AzuraCast Docs build process
# Powered by Netlify

[build]
  base    = "docs"
  publish = "docs/dist"
  command = "yarn run vuepress build ."

[[redirects]]
  from = "/api"
  to = "/api/index.html"
  status = 302
