# AzuraCast Docs build process
# Powered by Netlify

[build]
  base    = "util/docker/docs"
  publish = "../../../docs/public"
  command = "yarn run vuepress build ../../../docs"

[[redirects]]
  from = "/api"
  to = "/api/index.html"
  status = 302

[[redirects]]
  from = "/*"
  to = "/:splat.html"
  status = 302
  force = false
