---
- name: Install NodeJS and NPM
  shell: curl -L https://raw.githubusercontent.com/tj/n/master/bin/n -o n && bash n lts
  args:
    chdir: "/tmp"

- name: Pull Node Dependencies
  become: true
  become_user: azuracast
  shell: npm ci
  args:
    chdir: "{{ www_base }}/frontend"

- name: Build AzuraCast Frontend Scripts
  become: true
  become_user: azuracast
  shell: npm run build
  args:
    chdir: "{{ www_base }}/frontend"
