---
- name: Enable and restart all core services
  service:
    name: "{{ item }}"
    enabled: yes
    state: restarted
  with_items:
   - "influxdb"
   - "mysql"
   - "php7.4-fpm"
   - "nginx"
   - "redis"

- name: Pause to allow InfluxDB to spin up
  wait_for: port=8086 delay=5