---
- name: Download DBIP Database
  get_url:
    url: https://download.db-ip.com/free/dbip-city-lite-2020-03.mmdb.gz
    dest: "{{ app_base }}/dbip/dbip-city-lite.mmdb.gz"

- name: Extract DBIP Database
  shell: "gunzip dbip-city-lite.mmdb.gz"
  args:
    chdir: "{{ app_base }}/dbip"

- name: Set DBIP Database Permissions
  file:
    path: "{{ app_base }}/dbip/dbip-city-lite.mmdb"
    state: file
    mode: "u=rwx,g=rx,o=rx"
    owner: "azuracast"
    group: "www-data"
